# Generated by Django 3.0.8 on 2022-12-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('foto_objeto', models.ImageField(blank=True, null=True, upload_to='Objetos')),
            ],
        ),
        migrations.CreateModel(
            name='TiposDistraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PermisosObjetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Monitoreo.Objetos')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetos_tutor', to='Persona.Tutores')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_distraccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Monitoreo.TiposDistraccion')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_monitoreo', to='Persona.Tutores')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('imagen_evidencia', models.ImageField(blank=True, null=True, upload_to='Evidencias')),
                ('observacion', models.CharField(max_length=200)),
                ('supervisado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_supervisado', to='Persona.Supervisados')),
                ('tipo_distraccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_distraccion', to='Monitoreo.TiposDistraccion')),
            ],
        ),
        migrations.CreateModel(
            name='Camaras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ruta', models.CharField(max_length=150, unique=True)),
                ('habilitada', models.BooleanField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camaras_tutor', to='Persona.Tutores')),
            ],
        ),
    ]
