# Generated by Django 3.0.8 on 2023-01-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camaras',
            name='direccion_ruta',
            field=models.CharField(max_length=150),
        ),
    ]
